from django.conf.urls import patterns, url
from child import views
from child.preview import *
from .forms import *
from services.views import service_index, service_disposal


urlpatterns = patterns('',
        url(r'^$', service_index, {'type_label': 'child'}, name='index'),

        #url(r'^health_manual/$', service_disposal,
        #    {'content_form': HealthManualForm, 'type_label': 'child', 'item_label': 'health_manual'},
        #    name='health_manual'),
        #url(r'^newborn_family_visit/$', service_disposal,
        #    {'content_form': NewbornFamilyVisitForm, 'type_label': 'child', 'item_label': 'newborn_family_visit'},
        #    name='newborn_family_visit'),
        #url(r'^aftercare_1_month/$', service_disposal,
        #    {'content_form': Aftercare1MonthForm, 'type_label': 'child', 'item_label': 'aftercare_1_month'},
        #    name='aftercare_1_month'),
        #url(r'^aftercare_3_month/$', service_disposal,
        #    {'content_form': Aftercare3MonthForm, 'type_label': 'child', 'item_label': 'aftercare_3_month'},
        #    name='aftercare_3_month'),
        #url(r'^aftercare_6_month/$', service_disposal,
        #    {'content_form': Aftercare6MonthForm, 'type_label': 'child', 'item_label': 'aftercare_6_month'},
        #    name='aftercare_6_month'),
        #url(r'^aftercare_8_month/$', service_disposal,
        #    {'content_form': Aftercare8MonthForm, 'type_label': 'child', 'item_label': 'aftercare_8_month'},
        #    name='aftercare_8_month'),
        #url(r'^aftercare_12_month/$', service_disposal,
        #    {'content_form': Aftercare12MonthForm, 'type_label': 'child', 'item_label': 'aftercare_12_month'},
        #    name='aftercare_12_month'),
        #url(r'^aftercare_18_month/$', service_disposal,
        #    {'content_form': Aftercare18MonthForm, 'type_label': 'child', 'item_label': 'aftercare_18_month'},
        #    name='aftercare_18_month'),
        #url(r'^aftercare_24_month/$',service_disposal,
        #    {'content_form': Aftercare24MonthForm, 'type_label': 'child', 'item_label': 'aftercare_24_month'},
        #    name='aftercare_24_month'),
        #url(r'^aftercare_30_month/$', service_disposal,
        #    {'content_form': Aftercare30MonthForm, 'type_label': 'child', 'item_label': 'aftercare_30_month'},
        #    name='aftercare_30_month'),
        #url(r'^aftercare_3_year/$', service_disposal,
        #    {'content_form': Aftercare3YearForm, 'type_label': 'child', 'item_label': 'aftercare_3_year'},
        #    name='aftercare_3_year'),
        #url(r'^aftercare_4_year/$', service_disposal,
        #    {'content_form': Aftercare4YearForm, 'type_label': 'child', 'item_label': 'aftercare_4_year'},
        #    name='aftercare_4_year'),
        #url(r'^aftercare_5_year/$', service_disposal,
        #    {'content_form': Aftercare5YearForm, 'type_label': 'child', 'item_label': 'aftercare_5_year'},
        #    name='aftercare_5_year'),
        #url(r'^aftercare_6_year/$', service_disposal,
        #   {'content_form': Aftercare6YearForm, 'type_label': 'child', 'item_label': 'aftercare_6_year'},
        #    name='aftercare_6_year'),
        url(r'^newborn_family_visit/$', NewbornFamilyVisitFormPreview(NewbornFamilyVisitForm), name='newborn_family_visit'),
        url(r'^aftercare_1_month/$', Aftercare1MonthFormPreview(Aftercare1MonthForm), name='aftercare_1_month'),
        url(r'^aftercare_3_month/$', Aftercare3MonthFormPreview(Aftercare3MonthForm), name='aftercare_3_month'),
        url(r'^aftercare_6_month/$', Aftercare6MonthFormPreview(Aftercare6MonthForm), name='aftercare_6_month'),
        url(r'^aftercare_8_month/$', Aftercare8MonthFormPreview(Aftercare8MonthForm), name='aftercare_8_month'),
        url(r'^aftercare_12_month/$', Aftercare12MonthFormPreview(Aftercare12MonthForm), name='aftercare_12_month'),
        url(r'^aftercare_18_month/$', Aftercare18MonthFormPreview(Aftercare18MonthForm), name='aftercare_18_month'),
        url(r'^aftercare_24_month/$', Aftercare24MonthFormPreview(Aftercare24MonthForm), name='aftercare_24_month'),
        url(r'^aftercare_30_month/$', Aftercare30MonthFormPreview(Aftercare30MonthForm), name='aftercare_30_month'),
        url(r'^aftercare_3_year/$', Aftercare3YearFormPreview(Aftercare3YearForm), name='aftercare_3_year'),
        url(r'^aftercare_4_year/$', Aftercare4YearFormPreview(Aftercare4YearForm), name='aftercare_4_year'),
        url(r'^aftercare_5_year/$', Aftercare5YearFormPreview(Aftercare5YearForm), name='aftercare_5_year'),
        url(r'^aftercare_6_year/$', Aftercare6YearFormPreview(Aftercare6YearForm), name='aftercare_6_year'),
        url(r'^newborn_visit_submit/$', views.newborn_visit_submit, name='newborn_visit_submit'),
        url(r'^newborn_visit_review/$', views.newborn_visit_review, name='newborn_visit_review'),

        url(r'^newborn/$', views.newborn_page, name='newborn_page'),

        url(r'^health_0_1_page/$', views.health_0_1_page, name='health_0_1_page'),
        url(r'^health_0_1_review/$', views.health_0_1_review, name='health_0_1_review'),
        url(r'^health_0_1_form/$', views.health_0_1_form, name='health_0_1_form'),
        url(r'^health_0_1_submit/$', views.health_0_1_submit, name='health_0_1_submit'),

        url(r'^health_1_2_page/$', views.health_1_2_page, name='health_1_2_page'),
        url(r'^health_1_2_review/$', views.health_1_2_review, name='health_1_2_review'),
        url(r'^health_1_2_form/$', views.health_1_2_form, name='health_1_2_form'),
        url(r'^health_1_2_submit/$', views.health_1_2_submit, name='health_1_2_submit'),

        url(r'^health_3_6_page/$', views.health_3_6_page, name='health_3_6_page'),
        url(r'^health_3_6_review/$', views.health_3_6_review, name='health_3_6_review'),
        url(r'^health_3_6_form/$', views.health_3_6_form, name='health_3_6_form'),
        url(r'^health_3_6_submit/$', views.health_3_6_submit, name='health_3_6_submit'),
)