# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
#from psychiatric import views
from .forms import *
from psychiatric import views
from .preview import *
from services.views import service_index, service_disposal
from ehr.forms import PhysicalExaminationForm, BloodRoutineTestForm, BloodGlucoseForm, \
    ElectrocardiogramForm, AlanineAminotransferaseForm, GlutamicOxalaceticTransaminaseForm, PsyBodyCheckForm
from ehr.preview import PhyExamFormPreview

urlpatterns = patterns('',
        url(r'^$', service_index, {'type_label': 'psychiatric'}, name='index'),
        #url(r'^physical_examination/$', service_disposal,
        #    {'content_form': PhysicalExaminationForm, 'type_label': 'psychiatric', 'item_label': 'physical_examination'},
        #    name='physical_examination'),
        #url(r'^electrocardiogram/$', service_disposal,
        #    {'content_form': ElectrocardiogramForm, 'type_label': 'psychiatric', 'item_label': 'electrocardiogram'},
        #    name='electrocardiogram'),
        #url(r'^blood_glucose/$', service_disposal,
        #    {'content_form': BloodGlucoseForm, 'type_label': 'psychiatric', 'item_label': 'blood_glucose'},
        #    name='blood_glucose'),
        #url(r'^transaminase/$', service_disposal,
        #    {'content_form': TransaminaseForm, 'type_label': 'psychiatric', 'item_label': 'transaminase'},
        #    name='transaminase'),
        #url(r'^blood_routine_test/$', service_disposal,
        #    {'content_form': BloodRoutineTestForm, 'type_label': 'psychiatric', 'item_label': 'blood_routine_test'},
        #    name='blood_routine_test'),
        #url(r'^aftercare_1/$', service_disposal,
        #    {'content_form': Aftercare1Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_1'},
        #    name='aftercare_1'),

        # 精神病患者健康体检
        url(r'^body_check/$', PhyExamFormPreview(PsyBodyCheckForm),
            {'type_alias': 'psychiatric', 'item_alias': 'body_check', 'model_name': 'PsyBodyCheck'},
            name='psy_body_check'),

        url(r'^aftercare_1/$', PsyVisitFormPreview(Aftercare1Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_1', 'model_name': 'Aftercare1'},
            name='aftercare_1'),
        url(r'^aftercare_2/$', PsyVisitFormPreview(Aftercare2Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_2', 'model_name': 'Aftercare2'},
            name='aftercare_2'),
        url(r'^aftercare_3/$', PsyVisitFormPreview(Aftercare3Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_3', 'model_name': 'Aftercare3'},
            name='aftercare_3'),
        url(r'^aftercare_4/$', PsyVisitFormPreview(Aftercare4Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_4', 'model_name': 'Aftercare4'},
            name='aftercare_4'),
        url(r'^aftercare_5/$', PsyVisitFormPreview(Aftercare5Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_5', 'model_name': 'Aftercare5'},
            name='aftercare_5'),
        url(r'^aftercare_6/$', PsyVisitFormPreview(Aftercare6Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_6', 'model_name': 'Aftercare6'},
            name='aftercare_6'),
        url(r'^aftercare_7/$', PsyVisitFormPreview(Aftercare7Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_7', 'model_name': 'Aftercare7'},
            name='aftercare_7'),
        url(r'^aftercare_8/$', PsyVisitFormPreview(Aftercare8Form),
            {'type_alias': 'psychiatric', 'item_alias': 'aftercare_8', 'model_name': 'Aftercare8'},
            name='aftercare_8'),
        url(r'^physical_examination/$', PhyExamFormPreview(PhysicalExaminationForm),
            {'type_alias': 'psychiatric', 'item_alias': 'physical_examination', 'model_name': 'PhysicalExamination'},
            name='physical_examination'),
        url(r'^blood_routine_test/$', PhyExamFormPreview(BloodRoutineTestForm),
            {'type_alias': 'psychiatric', 'item_alias': 'blood_routine_test', 'model_name': 'BloodRoutineTest'},
            name='physical_examination'),
        url(r'^alanine_aminotransferase/$', PhyExamFormPreview(AlanineAminotransferaseForm),
            {'type_alias': 'psychiatric', 'item_alias': 'alanine_aminotransferase', 'model_name': 'AlanineAminotransferase'},
            name='alanine_aminotransferase'),
        url(r'^glutamic_oxalacetic_transaminase/$', PhyExamFormPreview(GlutamicOxalaceticTransaminaseForm),
            {'type_alias': 'psychiatric', 'item_alias': 'glutamic_oxalacetic_transaminase', 'model_name': 'GlutamicOxalaceticTransaminase'},
            name='glutamic_oxalacetic_transaminase'),
        url(r'^blood_glucose/$', PhyExamFormPreview(BloodGlucoseForm),
            {'type_alias': 'psychiatric', 'item_alias': 'blood_glucose', 'model_name': 'BloodGlucose'},
            name='blood_glucose'),
        url(r'^electrocardiogram/$', PhyExamFormPreview(ElectrocardiogramForm),
            {'type_alias': 'psychiatric', 'item_alias': 'electrocardiogram', 'model_name': 'Electrocardiogram'},
            name='electrocardiogram'),

        #url(r'^aftercare_5/$', PsyVisitFormPreview(Aftercare5Form), name='aftercare_5'),
        #url(r'^aftercare_2/$', service_disposal,
        #    {'content_form': Aftercare2Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_2'},
        #    name='aftercare_2'),
        #url(r'^aftercare_3/$', service_disposal,
        #    {'content_form': Aftercare3Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_3'},
        #    name='aftercare_3'),
        #url(r'^aftercare_4/$', service_disposal,
        #    {'content_form': Aftercare4Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_4'},
        #    name='aftercare_4'),
        #url(r'^aftercare_5/$', service_disposal,
        #    {'content_form': Aftercare5Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_5'},
        #    name='aftercare_5'),
        #url(r'^aftercare_6/$', service_disposal,
        #    {'content_form': Aftercare6Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_6'},
        #    name='aftercare_6'),
        #url(r'^aftercare_7/$', service_disposal,
        #    {'content_form': Aftercare7Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_7'},
        #    name='aftercare_7'),
        #url(r'^aftercare_8/$', service_disposal,
        #    {'content_form': Aftercare8Form, 'type_label': 'psychiatric', 'item_label': 'aftercare_8'},
        #    name='aftercare_8'),
    url(r'^aftercare_page/$', views.aftercare_page, name='aftercare_page'),
    url(r'^aftercare_form/$', views.aftercare_form, name='aftercare_form'),
    url(r'^aftercare_submit/$', views.aftercare_submit, name='aftercare_submit'),
    url(r'^aftercare_review/$', views.aftercare_review, name='aftercare_review'),

    url(r'^personal_info_page/$', views.personal_info_page, name='personal_info_page'),
    url(r'^personal_info_review/$', views.personal_info_review, name='personal_info_review'),
    url(r'^personal_info_submit/$', views.personal_info_submit, name='personal_info_submit'),

    url(r'^body_exam_page/$', views.body_exam_page, name='body_exam_page'),
    url(r'^body_exam_form/$', views.body_exam_form, name='body_exam_form'),
    url(r'^body_exam_submit/$', views.body_exam_submit, name='body_exam_submit'),

)
