from django.conf.urls import patterns, url
from education.forms import *
from education.previews import EducationRecordFormPreview
from education.views import service_disposal
from education import views

__author__ = 'Administrator'


urlpatterns = patterns('',
    url(r'^ad_board/$', service_disposal,
        {'content_form': AdBoardForm, 'type_label': 'education', 'item_label': 'ad_board'},
        name='ad_board'),
    url(r'^ad_board_update/$', service_disposal,
        {'content_form': AdBoardUpdateForm, 'type_label': 'education', 'item_label': 'ad_board_update'},
        name='ad_board_update'),
    url(r'^ad_book/$', service_disposal,
        {'content_form': AdBookForm, 'type_label': 'education', 'item_label': 'ad_book'},
        name='ad_book'),
    url(r'^ad_page/$', service_disposal,
        {'content_form': AdPageForm, 'type_label': 'education', 'item_label': 'ad_page'},
        name='ad_page'),
    url(r'^ad_booklet/$', service_disposal,
        {'content_form': AdBookletForm, 'type_label': 'education', 'item_label': 'ad_booklet'},
        name='ad_booklet'),
    url(r'^shelf/$', service_disposal,
        {'content_form': ShelfForm, 'type_label': 'education', 'item_label': 'shelf'},
        name='shelf'),
    url(r'^ad_board_maintenance/$', service_disposal,
        {'content_form': AdBoardMaintenanceForm, 'type_label': 'education', 'item_label': 'ad_board_maintenance'},
        name='ad_board_maintenance'),
    url(r'^video/$', service_disposal,
        {'content_form': VideoForm, 'type_label': 'education', 'item_label': 'video'},
        name='video'),
    url(r'^public_health_consultation/$', service_disposal,
        {'content_form': PublicHealthConsultationForm, 'type_label': 'education', 'item_label': 'public_health_consultation'},
        name='public_health_consultation'),
    url(r'^health_knowledge_lecture/$', service_disposal,
        {'content_form': HealthKnowledgeLectureForm, 'type_label': 'education', 'item_label': 'health_knowledge_lecture'},
        name='health_knowledge_lecture'),
    url(r'^health_education_website/$', service_disposal,
        {'content_form': HealthEducationWebsiteForm, 'type_label': 'education', 'item_label': 'health_education_website'},
        name='health_education_website'),
    url(r'^activity/$', views.activity_page, name='activity_page'),
    url(r'^activity_table/$', views.activity_table, name='activity_table'),
    url(r'^activity_list/$', views.activity_list, name='activity_list'),
    url(r'^activity_review/$', views.activity_review, name='activity_review'),

    #url(r'^health_educate/$', service_disposal,
    #    {'content_form': HealthEducateForm, 'type_label': 'education', 'item_label': 'health_educate'},
    #   name='health_educate')

    #    url(r'^ad_board/$', EducationRecordFormPreview(AdBoardForm),
    #        {'type_alias': 'education', 'item_alias': 'ad_board', 'form_name': AdBoardForm},
    #        name='ad_board'),
    #    url(r'^ad_board_update/$', EducationRecordFormPreview(AdBoardUpdateForm),
    #        {'type_alias': 'education', 'item_alias': 'ad_board_update', 'form_name': AdBoardUpdateForm},
    #        name='ad_board_update'),
    #    url(r'^ad_book/$', EducationRecordFormPreview(AdBookForm),
    #        {'type_alias': 'education', 'item_alias': 'ad_book', 'form_name': AdBookForm},
    #        name='ad_book'),
    #    url(r'^ad_page/$', EducationRecordFormPreview(AdPageForm),
    #        {'type_alias': 'education', 'item_alias': 'ad_page', 'form_name': AdPageForm},
    #        name='ad_page'),
    #    url(r'^ad_booklet/$', EducationRecordFormPreview(AdBookletForm),
    #        {'type_alias': 'education', 'item_alias': 'ad_booklet', 'form_name': AdBookletForm},
    #        name='ad_booklet'),
    #    url(r'^shelf/$', EducationRecordFormPreview(ShelfForm),
    #        {'type_alias': 'education', 'item_alias': 'shelf', 'form_name': ShelfForm},
    #        name='shelf'),
    #    url(r'^ad_board_maintenance/$', EducationRecordFormPreview(AdBoardMaintenanceForm),
    #        {'type_alias': 'education', 'item_alias': 'ad_board_maintenance', 'form_name': AdBoardMaintenanceForm},
    #        name='ad_board_maintenance'),
    #    url(r'^video/$', EducationRecordFormPreview(VideoForm),
    #        {'type_alias': 'education', 'item_alias': 'video', 'form_name': VideoForm},
    #        name='video'),
    #    url(r'^public_health_consultation/$', EducationRecordFormPreview(PublicHealthConsultationForm),
    #        {'type_alias': 'education', 'item_alias': 'public_health_consultation', 'form_name': PublicHealthConsultationForm},
    #        name='public_health_consultation'),
    #    url(r'^health_knowledge_lecture/$', EducationRecordFormPreview(HealthKnowledgeLectureForm),
    #        {'type_alias': 'education', 'item_alias': 'health_knowledge_lecture', 'form_name': HealthKnowledgeLectureForm},
    #        name='health_knowledge_lecture'),
    #    url(r'^health_education_website/$', EducationRecordFormPreview(HealthEducationWebsiteForm),
    #        {'type_alias': 'education', 'item_alias': 'health_education_website', 'form_name': HealthEducationWebsiteForm},
    #        name='health_education_website'),
)
