# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aftercare',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('gestational_weeks', models.PositiveSmallIntegerField(verbose_name=b'\xe5\xad\x95\xe5\x91\xa8')),
                ('complaint', models.TextField(max_length=100, verbose_name=b'\xe4\xb8\xbb\xe8\xaf\x89')),
                ('weight', models.FloatField(verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d')),
                ('examination_before_parturition_uteri_bottom_height', models.FloatField(verbose_name=b'\xe5\xae\xab\xe5\xba\x95\xe9\xab\x98\xe5\xba\xa6')),
                ('examination_before_parturition_abdomen_circumference', models.FloatField(verbose_name=b'\xe8\x85\xb9\xe5\x9b\xb4')),
                ('examination_before_parturition_fetus_position', models.CharField(max_length=50, verbose_name=b'\xe8\x83\x8e\xe4\xbd\x8d')),
                ('examination_before_parturition_fetal_heart_rate', models.FloatField(verbose_name=b'\xe8\x83\x8e\xe5\xbf\x83\xe7\x8e\x87')),
                ('sbp', models.FloatField(verbose_name=b'\xe6\x94\xb6\xe7\xbc\xa9\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\x88\x92\xe5\xbc\xa0\xe5\x8e\x8b')),
                ('hemoglobin', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd')),
                ('urine_protein', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd')),
                ('extra_auxiliary_examination', models.TextField(max_length=1000, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe8\xbe\x85\xe5\x8a\xa9\xe6\xa3\x80\xe6\x9f\xa5*', blank=True)),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('classification_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('transfer_treatment', models.CharField(max_length=5, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d', blank=True)),
                ('next_visit_date', models.DateField(max_length=10, null=True, verbose_name=b'\xe4\xb8\x8b\xe6\xac\xa1\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f', blank=True)),
            ],
            options={
                'db_table': 'pregnant_aftercare',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aftercare1',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe5\xa1\xab\xe8\xa1\xa8\xe6\x97\xa5\xe6\x9c\x9f')),
                ('weeks', models.IntegerField(null=True, verbose_name=b'\xe5\xa1\xab\xe8\xa1\xa8\xe5\xad\x95\xe5\x91\xa8', blank=True)),
                ('age', models.IntegerField(null=True, verbose_name=b'\xe5\xad\x95\xe5\xa6\x87\xe5\xb9\xb4\xe9\xbe\x84', blank=True)),
                ('husband_name', models.CharField(max_length=20, null=True, verbose_name=b'\xe4\xb8\x88\xe5\xa4\xab\xe5\xa7\x93\xe5\x90\x8d', blank=True)),
                ('husband_age', models.IntegerField(verbose_name=b'\xe4\xb8\x88\xe5\xa4\xab\xe5\xb9\xb4\xe9\xbe\x84')),
                ('husband_phone', models.CharField(max_length=20, null=True, verbose_name=b'\xe4\xb8\x88\xe5\xa4\xab\xe7\x94\xb5\xe8\xaf\x9d', blank=True)),
                ('pregnant_times', models.IntegerField(null=True, verbose_name=b'\xe5\xad\x95\xe6\xac\xa1', blank=True)),
                ('natural_production', models.IntegerField(null=True, verbose_name=b'\xe9\x98\xb4\xe9\x81\x93\xe5\x88\x86\xe5\xa8\xa9', blank=True)),
                ('surgery_production', models.IntegerField(null=True, verbose_name=b'\xe5\x89\x96\xe5\xae\xab\xe4\xba\xa7', blank=True)),
                ('last_menstruation', models.DateField(max_length=10, null=True, verbose_name=b'\xe6\x9c\xab\xe6\xac\xa1\xe6\x9c\x88\xe7\xbb\x8f', blank=True)),
                ('not_sure', models.NullBooleanField(verbose_name=b'\xe4\xb8\x8d\xe7\xa5\xa5')),
                ('due_date', models.DateField(max_length=10, null=True, verbose_name=b'\xe9\xa2\x84\xe4\xba\xa7\xe6\x9c\x9f', blank=True)),
                ('disease_history_other', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe6\x97\xa2\xe5\xbe\x80\xe5\x8f\xb2', blank=True)),
                ('family_history_other', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe5\xae\xb6\xe6\x97\x8f\xe5\x8f\xb2', blank=True)),
                ('personal_history_other', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe4\xb8\xaa\xe4\xba\xba\xe5\x8f\xb2', blank=True)),
                ('gynaecology_surgery_history', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\xa6\x87\xe7\xa7\x91\xe6\x89\x8b\xe6\x9c\xaf\xe5\x8f\xb2', choices=[('\u65e0', '\u65e0'), ('\u6709', '\u6709')])),
                ('gynaecology_surgery_name', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\xa6\x87\xe7\xa7\x91\xe6\x89\x8b\xe6\x9c\xaf\xe5\x90\x8d\xe7\xa7\xb0', blank=True)),
                ('miscarriage', models.IntegerField(null=True, verbose_name=b'\xe6\xb5\x81\xe4\xba\xa7', blank=True)),
                ('dead_fetus', models.IntegerField(null=True, verbose_name=b'\xe6\xad\xbb\xe8\x83\x8e', blank=True)),
                ('still_birth', models.IntegerField(null=True, verbose_name=b'\xe6\xad\xbb\xe4\xba\xa7', blank=True)),
                ('newnatal_death', models.IntegerField(null=True, verbose_name=b'\xe6\x96\xb0\xe7\x94\x9f\xe5\x84\xbf\xe6\xad\xbb\xe4\xba\xa1', blank=True)),
                ('birth_defect', models.IntegerField(null=True, verbose_name=b'\xe5\x87\xba\xe7\x94\x9f\xe7\xbc\xba\xe9\x99\xb7\xe5\x84\xbf', blank=True)),
                ('height', models.FloatField(null=True, verbose_name=b'\xe8\xba\xab\xe9\xab\x98', blank=True)),
                ('weight', models.FloatField(null=True, verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d', blank=True)),
                ('bmi', models.FloatField(null=True, verbose_name=b'\xe4\xbd\x93\xe8\xb4\xa8\xe6\x8c\x87\xe6\x95\xb0', blank=True)),
                ('sbp', models.IntegerField(null=True, verbose_name=b'\xe6\x94\xb6\xe7\xbc\xa9\xe5\x8e\x8b', blank=True)),
                ('dbp', models.IntegerField(null=True, verbose_name=b'\xe8\x88\x92\xe5\xbc\xa0\xe5\x8e\x8b', blank=True)),
                ('ausculate_heart', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\x90\xac\xe8\xaf\x8a\xe5\xbf\x83\xe8\x84\x8f', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('ausculate_heart_abnormal', models.CharField(max_length=30, null=True, verbose_name=b'\xe5\x90\xac\xe8\xaf\x8a\xe5\xbf\x83\xe8\x84\x8f\xe5\xbc\x82\xe5\xb8\xb8', blank=True)),
                ('ausculate_lung', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\x90\xac\xe8\xaf\x8a\xe8\x82\xba\xe9\x83\xa8', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('ausculate_lung_abnormal', models.CharField(max_length=30, null=True, verbose_name=b'\xe5\x90\xac\xe8\xaf\x8a\xe8\x82\xba\xe9\x83\xa8\xe5\xbc\x82\xe5\xb8\xb8', blank=True)),
                ('vulva', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xa4\x96\xe9\x98\xb4', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('vulva_abnormal', models.CharField(max_length=50, null=True, verbose_name=b'', blank=True)),
                ('vagina', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x98\xb4\xe9\x81\x93', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('vagina_abnormal', models.CharField(max_length=50, null=True, verbose_name=b'', blank=True)),
                ('cervix', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xae\xab\xe9\xa2\x88', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('cervix_abnormal', models.CharField(max_length=50, null=True, verbose_name=b'', blank=True)),
                ('uteri', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\xae\xab\xe4\xbd\x93', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('uteri_abnormal', models.CharField(max_length=50, null=True, verbose_name=b'', blank=True)),
                ('accessory', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x99\x84\xe4\xbb\xb6', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('accessory_abnormal', models.CharField(max_length=50, null=True, verbose_name=b'', blank=True)),
                ('hemoglobin', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd\xe5\x80\xbc', blank=True)),
                ('leukocyte', models.FloatField(null=True, verbose_name=b'\xe7\x99\xbd\xe7\xbb\x86\xe8\x83\x9e\xe8\xae\xa1\xe6\x95\xb0\xe5\x80\xbc', blank=True)),
                ('thrombocyte', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe5\xb0\x8f\xe6\x9d\xbf\xe8\xae\xa1\xe6\x95\xb0\xe5\x80\xbc', blank=True)),
                ('blood_extra', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('urine_protein', models.CharField(max_length=10, null=True, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd', blank=True)),
                ('urine_glucose', models.CharField(max_length=10, null=True, verbose_name=b'\xe5\xb0\xbf\xe7\xb3\x96', blank=True)),
                ('urine_ket', models.CharField(max_length=10, null=True, verbose_name=b'\xe5\xb0\xbf\xe9\x85\xae\xe4\xbd\x93', blank=True)),
                ('urine_ery', models.CharField(max_length=10, null=True, verbose_name=b'\xe5\xb0\xbf\xe6\xbd\x9c\xe8\xa1\x80', blank=True)),
                ('urine_extra', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('blood_type_abo', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe8\xa1\x80\xe5\x9e\x8bABO', choices=[('A\u578b', 'A\u578b'), ('B\u578b', 'B\u578b'), ('O\u578b', 'O\u578b'), ('AB\u578b', 'AB\u578b'), ('\u5176\u4ed6', '\u5176\u4ed6')])),
                ('blood_type_abo_other', models.CharField(max_length=30, null=True, verbose_name=b'\xe8\xa1\x80\xe5\x9e\x8b\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('blood_type_rh', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe8\xa1\x80\xe5\x9e\x8bRh', choices=[('Rh\u9634\u6027', 'Rh\u9634\u6027'), ('Rh\u9633\u6027', 'Rh\u9633\u6027'), ('\u4e0d\u7965', '\u4e0d\u7965')])),
                ('blood_glucose', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe7\xb3\x96', blank=True)),
                ('sgpt', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe6\xb8\x85\xe8\xb0\xb7\xe4\xb8\x99\xe8\xbd\xac\xe6\xb0\xa8\xe9\x85\xb6', blank=True)),
                ('sgot', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe6\xb8\x85\xe8\xb0\xb7\xe8\x8d\x89\xe8\xbd\xac\xe6\xb0\xa8\xe9\x85\xb6', blank=True)),
                ('albumin', models.FloatField(null=True, verbose_name=b'\xe7\x99\xbd\xe8\x9b\x8b\xe7\x99\xbd', blank=True)),
                ('tbil', models.FloatField(null=True, verbose_name=b'\xe6\x80\xbb\xe8\x83\x86\xe7\xba\xa2\xe7\xb4\xa0', blank=True)),
                ('dbil', models.FloatField(null=True, verbose_name=b'\xe7\xbb\x93\xe5\x90\x88\xe8\x83\x86\xe7\xba\xa2\xe7\xb4\xa0', blank=True)),
                ('scr', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe6\xb8\x85\xe8\x82\x8c\xe9\x85\x90', blank=True)),
                ('bun', models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe5\xb0\xbf\xe7\xb4\xa0\xe6\xb0\xae', blank=True)),
                ('vaginal_secretion', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x98\xb4\xe9\x81\x93\xe5\x88\x86\xe6\xb3\x8c\xe7\x89\xa9', choices=[('\u672a\u89c1\u5f02\u5e38', '\u672a\u89c1\u5f02\u5e38'), ('\u6ef4\u866b', '\u6ef4\u866b'), ('\u5047\u4e1d\u9175\u6bcd\u83cc', '\u5047\u4e1d\u9175\u6bcd\u83cc'), ('\u5176\u4ed6', '\u5176\u4ed6')])),
                ('vaginal_secretion_other', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x98\xb4\xe9\x81\x93\xe5\x88\x86\xe6\xb3\x8c\xe7\x89\xa9\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('vaginal_clean_degree', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x98\xb4\xe9\x81\x93\xe6\xb8\x85\xe6\xb4\x81\xe5\xba\xa6', choices=[('I\u5ea6', 'I\u5ea6'), ('II\u5ea6', 'II\u5ea6'), ('III\u5ea6', 'III\u5ea6'), ('IV\u5ea6', 'IV\u5ea6')])),
                ('surface_antigen', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe8\xa1\xa8\xe9\x9d\xa2\xe6\x8a\x97\xe5\x8e\x9f', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('surface_antibody', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe8\xa1\xa8\xe9\x9d\xa2\xe6\x8a\x97\xe4\xbd\x93', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('e_antigen', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8ee\xe6\x8a\x97\xe5\x8e\x9f', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('e_antibody', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8ee\xe6\x8a\x97\xe4\xbd\x93', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('core_antibody', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe6\xa0\xb8\xe5\xbf\x83\xe6\x8a\x97\xe4\xbd\x93', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('vdrl', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\xa2\x85\xe6\xaf\x92\xe8\xa1\x80\xe6\xb8\x85\xe8\xaf\x95\xe9\xaa\x8c', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('hiv_antibody', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'HIV\xe6\x8a\x97\xe4\xbd\x93\xe6\xa3\x80\xe6\xb5\x8b', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('b_scan', models.CharField(max_length=50, null=True, verbose_name=b'B\xe8\xb6\x85', blank=True)),
                ('total_evaluation', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe6\x80\xbb\xe4\xbd\x93\xe8\xaf\x84\xe4\xbc\xb0\xe6\x8c\x87\xe5\xaf\xbc', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('total_evaluation_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x80\xbb\xe4\xbd\x93\xe8\xaf\x84\xe4\xbc\xb0\xe6\x8c\x87\xe5\xaf\xbc\xe5\xbc\x82\xe5\xb8\xb8', blank=True)),
                ('guide_other', models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xbf\x9d\xe5\x81\xa5\xe6\x8c\x87\xe5\xaf\xbc\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('transfer', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_reason', models.CharField(max_length=50, null=True, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_hospital', models.CharField(max_length=50, null=True, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('next_visit_date', models.DateField(max_length=10, verbose_name=b'\xe4\xb8\x8b\xe6\xac\xa1\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('doctor_signature', models.CharField(max_length=20, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d')),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aftercare2',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('gestational_weeks', models.PositiveSmallIntegerField(verbose_name=b'\xe5\xad\x95\xe5\x91\xa8')),
                ('complaint', models.TextField(max_length=100, verbose_name=b'\xe4\xb8\xbb\xe8\xaf\x89')),
                ('weight', models.FloatField(verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d')),
                ('examination_before_parturition_uteri_bottom_height', models.FloatField(verbose_name=b'\xe5\xae\xab\xe5\xba\x95\xe9\xab\x98\xe5\xba\xa6')),
                ('examination_before_parturition_abdomen_circumference', models.FloatField(verbose_name=b'\xe8\x85\xb9\xe5\x9b\xb4')),
                ('examination_before_parturition_fetus_position', models.CharField(max_length=50, verbose_name=b'\xe8\x83\x8e\xe4\xbd\x8d')),
                ('examination_before_parturition_fetal_heart_rate', models.FloatField(verbose_name=b'\xe8\x83\x8e\xe5\xbf\x83\xe7\x8e\x87')),
                ('sbp', models.FloatField(verbose_name=b'\xe6\x94\xb6\xe7\xbc\xa9\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\x88\x92\xe5\xbc\xa0\xe5\x8e\x8b')),
                ('hemoglobin', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd')),
                ('urine_protein', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd')),
                ('extra_auxiliary_examination', models.TextField(max_length=1000, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe8\xbe\x85\xe5\x8a\xa9\xe6\xa3\x80\xe6\x9f\xa5*', blank=True)),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('classification_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('transfer_treatment', models.CharField(max_length=5, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d', blank=True)),
                ('next_visit_date', models.DateField(max_length=10, verbose_name=b'\xe4\xb8\x8b\xe6\xac\xa1\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'db_table': 'pregnant_aftercare_2',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aftercare3',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('gestational_weeks', models.PositiveSmallIntegerField(verbose_name=b'\xe5\xad\x95\xe5\x91\xa8')),
                ('complaint', models.TextField(max_length=100, verbose_name=b'\xe4\xb8\xbb\xe8\xaf\x89')),
                ('weight', models.FloatField(verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d')),
                ('examination_before_parturition_uteri_bottom_height', models.FloatField(verbose_name=b'\xe5\xae\xab\xe5\xba\x95\xe9\xab\x98\xe5\xba\xa6')),
                ('examination_before_parturition_abdomen_circumference', models.FloatField(verbose_name=b'\xe8\x85\xb9\xe5\x9b\xb4')),
                ('examination_before_parturition_fetus_position', models.CharField(max_length=50, verbose_name=b'\xe8\x83\x8e\xe4\xbd\x8d')),
                ('examination_before_parturition_fetal_heart_rate', models.FloatField(verbose_name=b'\xe8\x83\x8e\xe5\xbf\x83\xe7\x8e\x87')),
                ('sbp', models.FloatField(verbose_name=b'\xe6\x94\xb6\xe7\xbc\xa9\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\x88\x92\xe5\xbc\xa0\xe5\x8e\x8b')),
                ('hemoglobin', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd')),
                ('urine_protein', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd')),
                ('extra_auxiliary_examination', models.TextField(max_length=1000, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe8\xbe\x85\xe5\x8a\xa9\xe6\xa3\x80\xe6\x9f\xa5*', blank=True)),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('classification_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('transfer_treatment', models.CharField(max_length=5, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d', blank=True)),
                ('next_visit_date', models.DateField(max_length=10, verbose_name=b'\xe4\xb8\x8b\xe6\xac\xa1\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'db_table': 'pregnant_aftercare_3',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aftercare4',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('gestational_weeks', models.PositiveSmallIntegerField(verbose_name=b'\xe5\xad\x95\xe5\x91\xa8')),
                ('complaint', models.TextField(max_length=100, verbose_name=b'\xe4\xb8\xbb\xe8\xaf\x89')),
                ('weight', models.FloatField(verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d')),
                ('examination_before_parturition_uteri_bottom_height', models.FloatField(verbose_name=b'\xe5\xae\xab\xe5\xba\x95\xe9\xab\x98\xe5\xba\xa6')),
                ('examination_before_parturition_abdomen_circumference', models.FloatField(verbose_name=b'\xe8\x85\xb9\xe5\x9b\xb4')),
                ('examination_before_parturition_fetus_position', models.CharField(max_length=50, verbose_name=b'\xe8\x83\x8e\xe4\xbd\x8d')),
                ('examination_before_parturition_fetal_heart_rate', models.FloatField(verbose_name=b'\xe8\x83\x8e\xe5\xbf\x83\xe7\x8e\x87')),
                ('sbp', models.FloatField(verbose_name=b'\xe6\x94\xb6\xe7\xbc\xa9\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\x88\x92\xe5\xbc\xa0\xe5\x8e\x8b')),
                ('hemoglobin', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd')),
                ('urine_protein', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd')),
                ('extra_auxiliary_examination', models.TextField(max_length=1000, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe8\xbe\x85\xe5\x8a\xa9\xe6\xa3\x80\xe6\x9f\xa5*', blank=True)),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('classification_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('transfer_treatment', models.CharField(max_length=5, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d', blank=True)),
                ('next_visit_date', models.DateField(max_length=10, verbose_name=b'\xe4\xb8\x8b\xe6\xac\xa1\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
            ],
            options={
                'db_table': 'pregnant_aftercare_4',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aftercare5',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('gestational_weeks', models.PositiveSmallIntegerField(verbose_name=b'\xe5\xad\x95\xe5\x91\xa8')),
                ('complaint', models.TextField(max_length=100, verbose_name=b'\xe4\xb8\xbb\xe8\xaf\x89')),
                ('weight', models.FloatField(verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d')),
                ('examination_before_parturition_uteri_bottom_height', models.FloatField(verbose_name=b'\xe5\xae\xab\xe5\xba\x95\xe9\xab\x98\xe5\xba\xa6')),
                ('examination_before_parturition_abdomen_circumference', models.FloatField(verbose_name=b'\xe8\x85\xb9\xe5\x9b\xb4')),
                ('examination_before_parturition_fetus_position', models.CharField(max_length=50, verbose_name=b'\xe8\x83\x8e\xe4\xbd\x8d')),
                ('examination_before_parturition_fetal_heart_rate', models.FloatField(verbose_name=b'\xe8\x83\x8e\xe5\xbf\x83\xe7\x8e\x87')),
                ('sbp', models.FloatField(verbose_name=b'\xe6\x94\xb6\xe7\xbc\xa9\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\x88\x92\xe5\xbc\xa0\xe5\x8e\x8b')),
                ('hemoglobin', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd')),
                ('urine_protein', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd')),
                ('extra_auxiliary_examination', models.TextField(max_length=1000, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe8\xbe\x85\xe5\x8a\xa9\xe6\xa3\x80\xe6\x9f\xa5*', blank=True)),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('classification_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('transfer_treatment', models.CharField(max_length=5, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, null=True, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d', blank=True)),
            ],
            options={
                'db_table': 'pregnant_aftercare_5',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AlanineAminotransferase',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sgpt', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe6\xb8\x85\xe8\xb0\xb7\xe4\xb8\x99\xe8\xbd\xac\xe6\xb0\xa8\xe9\x85\xb6')),
            ],
            options={
                'db_table': 'pregnant_alanine_aminotransferase',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BloodRoutineTest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hemoglobin', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd')),
                ('leukocyte', models.FloatField(null=True, verbose_name=b'\xe7\x99\xbd\xe7\xbb\x86\xe8\x83\x9e\xe8\xae\xa1\xe6\x95\xb0\xe5\x80\xbc', blank=True)),
                ('thrombocyte', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe5\xb0\x8f\xe6\x9d\xbf')),
                ('blood_extra', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
            ],
            options={
                'db_table': 'pregnant_blood_routine_test',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('blood_type_abo', models.CharField(max_length=10, verbose_name=b'\xe8\xa1\x80\xe5\x9e\x8bABO', choices=[('A\u578b', 'A\u578b'), ('B\u578b', 'B\u578b'), ('O\u578b', 'O\u578b'), ('AB\u578b', 'AB\u578b'), ('\u5176\u4ed6', '\u5176\u4ed6')])),
                ('blood_type_abo_other', models.CharField(max_length=30, null=True, verbose_name=b'\xe8\xa1\x80\xe5\x9e\x8b\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('blood_type_rh', models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe8\xa1\x80\xe5\x9e\x8bRh', choices=[('Rh\u9634\u6027', 'Rh\u9634\u6027'), ('Rh\u9633\u6027', 'Rh\u9633\u6027'), ('\u4e0d\u7965', '\u4e0d\u7965')])),
            ],
            options={
                'db_table': 'pregnant_blood_type',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BloodUreaNitrogen',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bun', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe5\xb0\xbf\xe7\xb4\xa0\xe6\xb0\xae')),
            ],
            options={
                'db_table': 'pregnant_blood_urea_nitrogen',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DiseaseHistoryChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FamilyHistoryChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GlutamicOxalaceticTransaminase',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('sgot', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe6\xb8\x85\xe8\xb0\xb7\xe8\x8d\x89\xe8\xbd\xac\xe6\xb0\xa8\xe9\x85\xb6')),
            ],
            options={
                'db_table': 'pregnant_glutamic_oxalacetic_transaminase',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Guide1Choices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Guide2Choices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Guide3Choices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Guide4Choices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Guide6Choices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GuideChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HepatitisBFiveItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('surface_antigen', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe8\xa1\xa8\xe9\x9d\xa2\xe6\x8a\x97\xe5\x8e\x9f', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('surface_antibody', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe8\xa1\xa8\xe9\x9d\xa2\xe6\x8a\x97\xe4\xbd\x93', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('e_antigen', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8ee\xe6\x8a\x97\xe5\x8e\x9f', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('e_antibody', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8ee\xe6\x8a\x97\xe4\xbd\x93', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
                ('core_antibody', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe6\xa0\xb8\xe5\xbf\x83\xe6\x8a\x97\xe4\xbd\x93', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')])),
            ],
            options={
                'db_table': 'pregnant_hepatitis_b_five_item',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PersonalHistoryChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Postpartum42Exam',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('general_health_situation', models.TextField(max_length=1000, verbose_name=b'\xe4\xb8\x80\xe8\x88\xac\xe5\x81\xa5\xe5\xba\xb7\xe6\x83\x85\xe5\x86\xb5')),
                ('general_mentality_situation', models.TextField(max_length=1000, verbose_name=b'\xe4\xb8\x80\xe8\x88\xac\xe5\xbf\x83\xe7\x90\x86\xe7\x8a\xb6\xe5\x86\xb5')),
                ('sbp', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe5\x8e\x8b')),
                ('breast', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\xb3\xe6\x88\xbf', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('breast_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('lochia', models.CharField(max_length=10, verbose_name=b'\xe6\x81\xb6\xe9\x9c\xb2', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('lochia_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('uterus', models.CharField(max_length=10, verbose_name=b'\xe5\xad\x90\xe5\xae\xab', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('uterus_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('wound', models.CharField(max_length=10, verbose_name=b'\xe4\xbc\xa4\xe5\x8f\xa3', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('wound_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('extra', models.TextField(null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d')),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u5df2\u6062\u590d', b'\xe5\xb7\xb2\xe6\x81\xa2\xe5\xa4\x8d'), ('\u672a\u6062\u590d', b'\xe6\x9c\xaa\xe6\x81\xa2\xe5\xa4\x8d')])),
                ('classification_not_recovery', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('dispose', models.CharField(max_length=5, verbose_name=b'\xe5\xa4\x84\xe7\x90\x86', choices=[('\u7ed3\u6848', b'\xe7\xbb\x93\xe6\xa1\x88'), ('\u8f6c\u8bca', b'\xe8\xbd\xac\xe8\xaf\x8a')])),
                ('dispose_transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('dispose_transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('guide', models.ManyToManyField(to='pregnant.Guide4Choices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True)),
            ],
            options={
                'db_table': 'pregnant_postpartum42_exam',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PostpartumVisit',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('visit_date', models.DateField(max_length=10, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('general_health_situation', models.TextField(max_length=1000, verbose_name=b'\xe4\xb8\x80\xe8\x88\xac\xe5\x81\xa5\xe5\xba\xb7\xe6\x83\x85\xe5\x86\xb5')),
                ('general_mentality_situation', models.TextField(max_length=1000, verbose_name=b'\xe4\xb8\x80\xe8\x88\xac\xe5\xbf\x83\xe7\x90\x86\xe7\x8a\xb6\xe5\x86\xb5')),
                ('sbp', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe5\x8e\x8b')),
                ('dbp', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe5\x8e\x8b')),
                ('breast', models.CharField(max_length=10, verbose_name=b'\xe4\xb9\xb3\xe6\x88\xbf', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('breast_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('lochia', models.CharField(max_length=10, verbose_name=b'\xe6\x81\xb6\xe9\x9c\xb2', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('lochia_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('uterus', models.CharField(max_length=10, verbose_name=b'\xe5\xad\x90\xe5\xae\xab', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('uterus_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('wound', models.CharField(max_length=10, verbose_name=b'\xe4\xbc\xa4\xe5\x8f\xa3', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('wound_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('extra', models.TextField(null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
                ('doctor_signature', models.CharField(max_length=20, verbose_name=b'\xe9\x9a\x8f\xe8\xae\xbf\xe5\x8c\xbb\xe7\x94\x9f\xe7\xad\xbe\xe5\x90\x8d')),
                ('body_temperature', models.FloatField(verbose_name=b'\xe4\xbd\x93\xe6\xb8\xa9')),
                ('classification', models.CharField(max_length=10, verbose_name=b'\xe5\x88\x86\xe7\xb1\xbb', choices=[('\u672a\u89c1\u5f02\u5e38', b'\xe6\x9c\xaa\xe8\xa7\x81\xe5\xbc\x82\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')])),
                ('classification_abnormal', models.CharField(max_length=100, null=True, verbose_name=b'', blank=True)),
                ('guide_extra', models.CharField(max_length=30, null=True, verbose_name=b'', blank=True)),
                ('transfer_treatment', models.CharField(max_length=5, verbose_name=b'\xe8\xbd\xac\xe8\xaf\x8a', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')])),
                ('transfer_treatment_reason', models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x8e\x9f\xe5\x9b\xa0', blank=True)),
                ('transfer_treatment_institution', models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\x84\xe5\x8f\x8a\xe7\xa7\x91\xe5\xae\xa4', blank=True)),
                ('next_visit_date', models.DateField(max_length=10, verbose_name=b'\xe4\xb8\x8b\xe6\xac\xa1\xe9\x9a\x8f\xe8\xae\xbf\xe6\x97\xa5\xe6\x9c\x9f')),
                ('guide', models.ManyToManyField(to='pregnant.Guide3Choices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True)),
            ],
            options={
                'db_table': 'pregnant_postpartum_visit',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SerumCreatinine',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('scr', models.FloatField(verbose_name=b'\xe8\xa1\x80\xe6\xb8\x85\xe8\x82\x8c\xe9\x85\x90')),
            ],
            options={
                'db_table': 'pregnant_serum_creatinine',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TotalBilirubin',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('tbil', models.FloatField(verbose_name=b'\xe6\x80\xbb\xe8\x83\x86\xe7\xba\xa2\xe7\xb4\xa0')),
            ],
            options={
                'db_table': 'pregnant_total_bilirubin',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='UrineRoutineTest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('urine_protein', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe8\x9b\x8b\xe7\x99\xbd')),
                ('urine_glucose', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe7\xb3\x96')),
                ('urine_ket', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe9\x85\xae\xe4\xbd\x93')),
                ('urine_ery', models.CharField(max_length=10, verbose_name=b'\xe5\xb0\xbf\xe6\xbd\x9c\xe8\xa1\x80')),
                ('urine_extra', models.CharField(max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True)),
            ],
            options={
                'db_table': 'pregnant_urine_routine_test',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='aftercare5',
            name='guide',
            field=models.ManyToManyField(to='pregnant.Guide2Choices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare4',
            name='guide',
            field=models.ManyToManyField(to='pregnant.Guide2Choices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare3',
            name='guide',
            field=models.ManyToManyField(to='pregnant.Guide1Choices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare2',
            name='guide',
            field=models.ManyToManyField(to='pregnant.GuideChoices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare1',
            name='disease_history',
            field=models.ManyToManyField(to='pregnant.DiseaseHistoryChoices', null=True, verbose_name=b'\xe6\x97\xa2\xe5\xbe\x80\xe5\x8f\xb2', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare1',
            name='family_history',
            field=models.ManyToManyField(to='pregnant.FamilyHistoryChoices', null=True, verbose_name=b'\xe5\xae\xb6\xe6\x97\x8f\xe5\x8f\xb2', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare1',
            name='guide',
            field=models.ManyToManyField(to='pregnant.Guide6Choices', null=True, verbose_name=b'\xe4\xbf\x9d\xe5\x81\xa5\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare1',
            name='personal_history',
            field=models.ManyToManyField(to='pregnant.PersonalHistoryChoices', null=True, verbose_name=b'\xe4\xb8\xaa\xe4\xba\xba\xe5\x8f\xb2', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='aftercare',
            name='guide',
            field=models.ManyToManyField(to='pregnant.Guide2Choices', null=True, verbose_name=b'\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
    ]
