# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_auto_20151203_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='CerebrovascularChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DangerousFactorChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DietHabitChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EyeChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HealthGuideChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HeartChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='KidneyChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='LiquorKindChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VesselChoices',
            fields=[
                ('choice', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='abnormal_1',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\xbc\x82\xe5\xb8\xb81', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='abnormal_2',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\xbc\x82\xe5\xb8\xb82', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='abnormal_3',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\xbc\x82\xe5\xb8\xb83', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='abnormal_4',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\xbc\x82\xe5\xb8\xb84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='acrotarsium_artery_pulse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xb6\xb3\xe8\x83\x8c\xe5\x8a\xa8\xe8\x84\x89\xe6\x90\x8f\xe5\x8a\xa8', choices=[('\u672a\u89e6\u53ca', b'\xe6\x9c\xaa\xe8\xa7\xa6\xe5\x8f\x8a'), ('\u89e6\u53ca\u53cc\u4fa7\u5bf9\u79f0', b'\xe8\xa7\xa6\xe5\x8f\x8a\xe5\x8f\x8c\xe4\xbe\xa7\xe5\xaf\xb9\xe7\xa7\xb0'), ('\u89e6\u53ca\u5de6\u4fa7\u5f31\u6216\u6d88\u5931', b'\xe8\xa7\xa6\xe5\x8f\x8a\xe5\xb7\xa6\xe4\xbe\xa7\xe5\xbc\xb1\xe6\x88\x96\xe6\xb6\x88\xe5\xa4\xb1'), ('\u89e6\u53ca\u53f3\u4fa7\u5f31\u6216\u6d88\u5931', b'\xe8\xa7\xa6\xe5\x8f\x8a\xe5\x8f\xb3\xe4\xbe\xa7\xe5\xbc\xb1\xe6\x88\x96\xe6\xb6\x88\xe5\xa4\xb1')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='albumin',
            field=models.FloatField(null=True, verbose_name=b'\xe7\x99\xbd\xe8\x9b\x8b\xe7\x99\xbd', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='b_ultrasonic_abnormal',
            field=models.CharField(max_length=100, null=True, verbose_name=b'B\xe8\xb6\x85', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='blood_potassium_concentration',
            field=models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe9\x92\xbe\xe6\xb5\x93\xe5\xba\xa6', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='blood_sodium_concentration',
            field=models.FloatField(null=True, verbose_name=b'\xe8\xa1\x80\xe9\x92\xa0\xe6\xb5\x93\xe5\xba\xa6', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='cardiac',
            field=models.ManyToManyField(to='ehr.HeartChoices', null=True, verbose_name=b'\xe5\xbf\x83\xe8\x84\x8f\xe7\x96\xbe\xe7\x97\x85', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='cardiac_extra',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe5\xbf\x83\xe8\x84\x8f\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='cerebrovascular',
            field=models.ManyToManyField(to='ehr.CerebrovascularChoices', null=True, verbose_name=b'\xe8\x84\x91\xe8\xa1\x80\xe7\xae\xa1\xe7\x96\xbe\xe7\x97\x85', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='cerebrovascular_extra',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe8\x84\x91\xe8\xa1\x80\xe7\xae\xa1\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='cervical_smear',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\x83\xb8\xe9\x83\xa8X\xe7\xba\xbf\xe7\x89\x87\xe2\x80\x94\xe2\x80\x94\xe6\xad\xa3\xe5\xb8\xb8\xe5\xbc\x82\xe5\xb8\xb8', choices=[('\u6b63\u5e38', b'\xe6\xad\xa3\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='cervical_smear_abnormal',
            field=models.CharField(max_length=20, null=True, verbose_name=b'\xe8\x83\xb8\xe9\x83\xa8X\xe7\xba\xbf\xe7\x89\x87\xe2\x80\x94\xe2\x80\x94\xe5\xbc\x82\xe5\xb8\xb8', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='chest_x_ray',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'', choices=[('\u6b63\u5e38', b'\xe6\xad\xa3\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='chest_x_ray_abnormal',
            field=models.CharField(max_length=100, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='conjugated_bilirubin',
            field=models.FloatField(null=True, verbose_name=b'\xe7\xbb\x93\xe5\x90\x88\xe8\x83\x86\xe7\xba\xa2\xe7\xb4\xa0', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='dangerous_factor_control',
            field=models.ManyToManyField(to='ehr.DangerousFactorChoices', null=True, verbose_name=b'\xe5\x8d\xb1\xe9\x99\xa9\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa7\xe5\x88\xb6', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='diet_habit',
            field=models.ManyToManyField(to='ehr.DietHabitChoices', null=True, verbose_name=b'\xe9\xa5\xae\xe9\xa3\x9f\xe4\xb9\xa0\xe6\x83\xaf', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='exercise_rate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe9\x94\xbb\xe7\x82\xbc\xe9\xa2\x91\xe7\x8e\x87', choices=[('\u6bcf\u5929', b'\xe6\xaf\x8f\xe5\xa4\xa9'), ('\u6bcf\u5468\u4e00\u6b21\u4ee5\u4e0a', b'\xe6\xaf\x8f\xe5\x91\xa8\xe4\xb8\x80\xe6\xac\xa1\xe4\xbb\xa5\xe4\xb8\x8a'), ('\u5076\u5c14', b'\xe5\x81\xb6\xe5\xb0\x94'), ('\u4e0d\u953b\u70bc', b'\xe4\xb8\x8d\xe9\x94\xbb\xe7\x82\xbc')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='exercise_time',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe6\xaf\x8f\xe6\xac\xa1\xe9\x94\xbb\xe7\x82\xbc\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='exercise_way',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe9\x94\xbb\xe7\x82\xbc\xe6\x96\xb9\xe5\xbc\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='exercise_years',
            field=models.FloatField(null=True, verbose_name=b'\xe5\x9d\x9a\xe6\x8c\x81\xe9\x94\xbb\xe7\x82\xbc\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='extra',
            field=models.CharField(max_length=500, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='extra_system',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x96\xbe\xe7\x97\x85', choices=[('\u672a\u53d1\u73b0', b'\xe6\x9c\xaa\xe5\x8f\x91\xe7\x8e\xb0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='extra_system_yes',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe5\x85\xb6\xe4\xbb\x96\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe6\x9c\x89', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='eye',
            field=models.ManyToManyField(to='ehr.EyeChoices', null=True, verbose_name=b'\xe7\x9c\xbc\xe9\x83\xa8\xe7\x96\xbe\xe7\x97\x85', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='eye_extra',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe7\x9c\xbc\xe9\x83\xa8\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_build_date_1',
            field=models.DateField(null=True, verbose_name=b'\xe5\xae\xb6\xe5\xba\xad\xe7\x97\x85\xe5\xba\x8a\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\xbb\xba\xe5\xba\x8a\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_build_date_2',
            field=models.DateField(null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_case_number_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\xae\xb6\xe5\xba\xad\xe7\x97\x85\xe5\xba\x8a\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe7\x97\x85\xe6\xa1\x88\xe5\x8f\xb7', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_case_number_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_medical_institution_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\xae\xb6\xe5\xba\xad\xe7\x97\x85\xe5\xba\x8a\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\x8c\xbb\xe7\x96\x97\xe6\x9c\xba\xe6\x9e\x84\xe5\x90\x8d\xe7\xa7\xb0', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_medical_institution_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_reason_1',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\xae\xb6\xe5\xba\xad\xe7\x97\x85\xe5\xba\x8a\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\x8e\x9f\xe5\x9b\xa0', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_reason_2',
            field=models.CharField(max_length=200, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_remove_date_1',
            field=models.DateField(null=True, verbose_name=b'\xe5\xae\xb6\xe5\xba\xad\xe7\x97\x85\xe5\xba\x8a\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe6\x92\xa4\xe5\xba\x8a\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='family_bed_history_remove_date_2',
            field=models.DateField(null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='fecal_occult_blood',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\xa4\xa7\xe4\xbe\xbf\xe6\xbd\x9c\xe8\xa1\x80', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='glycosylated_hemoglobin',
            field=models.FloatField(null=True, verbose_name=b'\xe7\xb3\x96\xe5\x8c\x96\xe8\xa1\x80\xe7\xba\xa2\xe8\x9b\x8b\xe7\x99\xbd', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='guide_extra',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\x8d\xb1\xe9\x99\xa9\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa7\xe5\x88\xb6\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='health_guide',
            field=models.ManyToManyField(to='ehr.HealthGuideChoices', null=True, verbose_name=b'\xe5\x81\xa5\xe5\xba\xb7\xe6\x8c\x87\xe5\xaf\xbc', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hepatitis_b_surface_antigen',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe4\xb9\x99\xe5\x9e\x8b\xe8\x82\x9d\xe7\x82\x8e\xe8\xa1\xa8\xe9\x9d\xa2\xe6\x8a\x97\xe5\x8e\x9f', choices=[('\u9634\u6027', b'\xe9\x98\xb4\xe6\x80\xa7'), ('\u9633\u6027', b'\xe9\x98\xb3\xe6\x80\xa7')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_case_number_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xbd\x8f\xe9\x99\xa2\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe7\x97\x85\xe6\xa1\x88\xe5\x8f\xb7', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_case_number_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_in_date_1',
            field=models.DateField(null=True, verbose_name=b'\xe4\xbd\x8f\xe9\x99\xa2\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\x85\xa5\xe9\x99\xa2\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_in_date_2',
            field=models.DateField(null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_medical_institution_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe4\xbd\x8f\xe9\x99\xa2\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\x8c\xbb\xe7\x96\x97\xe6\x9c\xba\xe6\x9e\x84\xe5\x90\x8d\xe7\xa7\xb0', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_medical_institution_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_out_date_1',
            field=models.DateField(null=True, verbose_name=b'\xe4\xbd\x8f\xe9\x99\xa2\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\x87\xba\xe9\x99\xa2\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_out_date_2',
            field=models.DateField(null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_reason_1',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe4\xbd\x8f\xe9\x99\xa2\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\x8e\x9f\xe5\x9b\xa0', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='hospitalization_history_reason_2',
            field=models.CharField(max_length=200, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='kidney',
            field=models.ManyToManyField(to='ehr.KidneyChoices', null=True, verbose_name=b'\xe8\x82\xbe\xe8\x84\x8f\xe7\x96\xbe\xe7\x97\x85', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='kidney_extra',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe8\x82\xbe\xe8\x84\x8f\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='legs_edema',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe4\xb8\x8b\xe8\x82\xa2\xe6\xb0\xb4\xe8\x82\xbf', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u5355\u4fa7', b'\xe5\x8d\x95\xe4\xbe\xa7'), ('\u53cc\u4fa7\u4e0d\u5bf9\u79f0', b'\xe5\x8f\x8c\xe4\xbe\xa7\xe4\xb8\x8d\xe5\xaf\xb9\xe7\xa7\xb0'), ('\u53cc\u4fa7\u5bf9\u79f0', b'\xe5\x8f\x8c\xe4\xbe\xa7\xe5\xaf\xb9\xe7\xa7\xb0')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_begin_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe9\xa5\xae\xe9\x85\x92\xe5\xb9\xb4\xe9\xbe\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_cessation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x88\x92\xe9\x85\x92', choices=[('\u672a\u6212\u9152', b'\xe6\x9c\xaa\xe6\x88\x92\xe9\x85\x92'), ('\u5df2\u6212\u9152', b'\xe5\xb7\xb2\xe6\x88\x92\xe9\x85\x92')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_cessation_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe6\x88\x92\xe9\x85\x92\xe5\xb9\xb4\xe9\xbe\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_day',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe6\x97\xa5\xe9\xa5\xae\xe9\x85\x92\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_drunkenness',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe8\xbf\x91\xe4\xb8\x80\xe5\xb9\xb4\xe5\x86\x85\xe6\x98\xaf\xe5\x90\xa6\xe6\x9b\xbe\xe9\x86\x89\xe9\x85\x92', choices=[('\u662f', b'\xe6\x98\xaf'), ('\u5426', b'\xe5\x90\xa6')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_kind',
            field=models.ManyToManyField(to='ehr.LiquorKindChoices', null=True, verbose_name=b'\xe9\xa5\xae\xe9\x85\x92\xe7\xa7\x8d\xe7\xb1\xbb', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_kind_extra',
            field=models.CharField(max_length=20, null=True, verbose_name=b'', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='liquor_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe9\xa5\xae\xe9\x85\x92\xe9\xa2\x91\xe7\x8e\x87', choices=[('\u4ece\u4e0d', b'\xe4\xbb\x8e\xe4\xb8\x8d'), ('\u5076\u5c14', b'\xe5\x81\xb6\xe5\xb0\x94'), ('\u7ecf\u5e38', b'\xe7\xbb\x8f\xe5\xb8\xb8'), ('\u6bcf\u5929', b'\xe6\xaf\x8f\xe5\xa4\xa9')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='lose_weight',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe5\x8d\xb1\xe9\x99\xa9\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa7\xe5\x88\xb6\xe2\x80\x94\xe2\x80\x94\xe5\x87\x8f\xe4\xbd\x93\xe9\x87\x8d\xe2\x80\x94\xe2\x80\x94\xe7\x9b\xae\xe6\xa0\x87', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='nervous_system',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\xa5\x9e\xe7\xbb\x8f\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x96\xbe\xe7\x97\x85', choices=[('\u672a\u53d1\u73b0', b'\xe6\x9c\xaa\xe5\x8f\x91\xe7\x8e\xb0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='nervous_system_yes',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe7\xa5\x9e\xe7\xbb\x8f\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe6\x9c\x89', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='normal_or_abnormal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x97\xa0\xe5\xbc\x82\xe5\xb8\xb8\xe2\x80\x94\xe2\x80\x94\xe6\x9c\x89\xe5\xbc\x82\xe5\xb8\xb8', choices=[('\u4f53\u68c0\u65e0\u5f02\u5e38', b'\xe6\x9c\x89\xe5\xbc\x82\xe5\xb8\xb8'), ('\u4f53\u68c0\u65e0\u5f02\u5e38', b'\xe6\x9c\x89\xe5\xbc\x82\xe5\xb8\xb8')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_chemical',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe5\x8c\x96\xe5\xad\xa6\xe7\x89\xa9\xe8\xb4\xa8', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_chemical_safeguard',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe5\x8c\x96\xe5\xad\xa6\xe7\x89\xa9\xe8\xb4\xa8\xe2\x80\x94\xe2\x80\x94\xe9\x98\xb2\xe6\x8a\xa4\xe6\x8e\xaa\xe6\x96\xbd', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_chemical_yes',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_dust',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe7\xb2\x89\xe5\xb0\x98', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_dust_safeguard',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe7\xb2\x89\xe5\xb0\x98\xe2\x80\x94\xe2\x80\x94\xe9\x98\xb2\xe6\x8a\xa4\xe6\x8e\xaa\xe6\x96\xbd', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_dust_yes',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_employment',
            field=models.FloatField(null=True, verbose_name=b'\xe8\x81\x8c\xe4\xb8\x9a\xe7\x97\x85\xe5\x8d\xb1\xe5\xae\xb3\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa5\xe8\xa7\xa6\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe4\xbb\x8e\xe4\xb8\x9a\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_extra',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_extra_safeguard',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96\xe2\x80\x94\xe2\x80\x94\xe9\x98\xb2\xe6\x8a\xa4\xe6\x8e\xaa\xe6\x96\xbd', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_extra_yes',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_physical',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe7\x89\xa9\xe7\x90\x86\xe5\x9b\xa0\xe7\xb4\xa0', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_physical_safeguard',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe7\x89\xa9\xe7\x90\x86\xe5\x9b\xa0\xe7\xb4\xa0\xe2\x80\x94\xe2\x80\x94\xe9\x98\xb2\xe6\x8a\xa4\xe6\x8e\xaa\xe6\x96\xbd', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_physical_yes',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_profession',
            field=models.CharField(max_length=20, null=True, verbose_name=b'\xe8\x81\x8c\xe4\xb8\x9a\xe7\x97\x85\xe5\x8d\xb1\xe5\xae\xb3\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa5\xe8\xa7\xa6\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe5\xb7\xa5\xe7\xa7\x8d', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_radioactive',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe6\x94\xbe\xe5\xb0\x84\xe7\x89\xa9\xe8\xb4\xa8', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_radioactive_safeguard',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe6\xaf\x92\xe7\x89\xa9\xe7\xa7\x8d\xe7\xb1\xbb\xe2\x80\x94\xe2\x80\x94\xe6\x94\xbe\xe5\xb0\x84\xe7\x89\xa9\xe8\xb4\xa8\xe2\x80\x94\xe2\x80\x94\xe9\x98\xb2\xe6\x8a\xa4\xe6\x8e\xaa\xe6\x96\xbd', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_radioactive_yes',
            field=models.CharField(max_length=50, null=True, blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='occupational_disease_yes_or_not',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name=b'\xe8\x81\x8c\xe4\xb8\x9a\xe7\x97\x85\xe5\x8d\xb1\xe5\xae\xb3\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa5\xe8\xa7\xa6\xe5\x8f\xb2\xe2\x80\x94\xe2\x80\x94\xe6\x9c\x89\xe6\x97\xa0', choices=[('\u65e0', b'\xe6\x97\xa0'), ('\u6709', b'\xe6\x9c\x89')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='old_health_situation_appraisal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe8\x80\x81\xe5\xb9\xb4\xe4\xba\xba\xe5\x81\xa5\xe5\xba\xb7\xe7\x8a\xb6\xe6\x80\x81\xe8\x87\xaa\xe6\x88\x91\xe8\xaf\x84\xe4\xbc\xb0*', choices=[('\u6ee1\u610f', b'\xe6\xbb\xa1\xe6\x84\x8f'), ('\u57fa\u672c\u6ee1\u610f', b'\xe5\x9f\xba\xe6\x9c\xac\xe6\xbb\xa1\xe6\x84\x8f'), ('\u8bf4\u4e0d\u6e05\u695a', b'\xe8\xaf\xb4\xe4\xb8\x8d\xe6\xb8\x85\xe6\xa5\x9a'), ('\u4e0d\u592a\u6ee1\u610f', b'\xe4\xb8\x8d\xe5\xa4\xaa\xe6\xbb\xa1\xe6\x84\x8f'), ('\u4e0d\u6ee1\u610f', b'\xe4\xb8\x8d\xe6\xbb\xa1\xe6\x84\x8f')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='old_living_selfcare_appraisal',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x80\x81\xe5\xb9\xb4\xe4\xba\xba\xe7\x94\x9f\xe6\xb4\xbb\xe8\x87\xaa\xe7\x90\x86\xe8\x83\xbd\xe5\x8a\x9b\xe8\x87\xaa\xe6\x88\x91\xe8\xaf\x84\xe4\xbc\xb0*', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='smoke_begin_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe5\x90\xb8\xe7\x83\x9f\xe5\xb9\xb4\xe9\xbe\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='smoke_cessation_age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe6\x88\x92\xe7\x83\x9f\xe5\xb9\xb4\xe9\xbe\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='smoke_day',
            field=models.PositiveSmallIntegerField(null=True, verbose_name=b'\xe6\x97\xa5\xe5\x90\xb8\xe7\x83\x9f\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='smoke_situation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe5\x90\xb8\xe7\x83\x9f\xe7\x8a\xb6\xe5\x86\xb5', choices=[('\u4ece\u4e0d\u5438\u70df', b'\xe4\xbb\x8e\xe4\xb8\x8d\xe5\x90\xb8\xe7\x83\x9f'), ('\u5df2\u6212\u70df', b'\xe5\xb7\xb2\xe6\x88\x92\xe7\x83\x9f'), ('\u5438\u70df', b'\xe5\x90\xb8\xe7\x83\x9f')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x8d\xaf\xe7\x89\xa9\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_1_method',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\xb3\x95', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_1_period',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe8\x8d\xaf\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_1_take_medicine_compliance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe8\x8d\xaf\xe4\xbe\x9d\xe4\xbb\x8e\xe6\x80\xa7', choices=[('\u89c4\u5f8b', b'\xe8\xa7\x84\xe5\xbe\x8b'), ('\u95f4\u65ad', b'\xe9\x97\xb4\xe6\x96\xad'), ('\u4e0d\u670d\u836f', b'\xe4\xb8\x8d\xe6\x9c\x8d\xe8\x8d\xaf')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_1_volume',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x8d\xaf\xe7\x89\xa9\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_2_method',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\xb3\x95', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_2_period',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe8\x8d\xaf\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_2_take_medicine_compliance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe8\x8d\xaf\xe4\xbe\x9d\xe4\xbb\x8e\xe6\x80\xa7', choices=[('\u89c4\u5f8b', b'\xe8\xa7\x84\xe5\xbe\x8b'), ('\u95f4\u65ad', b'\xe9\x97\xb4\xe6\x96\xad'), ('\u4e0d\u670d\u836f', b'\xe4\xb8\x8d\xe6\x9c\x8d\xe8\x8d\xaf')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_2_volume',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_3',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x8d\xaf\xe7\x89\xa9\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_3_method',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\xb3\x95', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_3_period',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe8\x8d\xaf\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_3_take_medicine_compliance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe8\x8d\xaf\xe4\xbe\x9d\xe4\xbb\x8e\xe6\x80\xa7', choices=[('\u89c4\u5f8b', b'\xe8\xa7\x84\xe5\xbe\x8b'), ('\u95f4\u65ad', b'\xe9\x97\xb4\xe6\x96\xad'), ('\u4e0d\u670d\u836f', b'\xe4\xb8\x8d\xe6\x9c\x8d\xe8\x8d\xaf')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_3_volume',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_4',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x8d\xaf\xe7\x89\xa9\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_4_method',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\xb3\x95', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_4_period',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe8\x8d\xaf\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_4_take_medicine_compliance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe8\x8d\xaf\xe4\xbe\x9d\xe4\xbb\x8e\xe6\x80\xa7', choices=[('\u89c4\u5f8b', b'\xe8\xa7\x84\xe5\xbe\x8b'), ('\u95f4\u65ad', b'\xe9\x97\xb4\xe6\x96\xad'), ('\u4e0d\u670d\u836f', b'\xe4\xb8\x8d\xe6\x9c\x8d\xe8\x8d\xaf')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_4_volume',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_5',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x8d\xaf\xe7\x89\xa9\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_5_method',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\xb3\x95', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_5_period',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe8\x8d\xaf\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_5_take_medicine_compliance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe8\x8d\xaf\xe4\xbe\x9d\xe4\xbb\x8e\xe6\x80\xa7', choices=[('\u89c4\u5f8b', b'\xe8\xa7\x84\xe5\xbe\x8b'), ('\u95f4\u65ad', b'\xe9\x97\xb4\xe6\x96\xad'), ('\u4e0d\u670d\u836f', b'\xe4\xb8\x8d\xe6\x9c\x8d\xe8\x8d\xaf')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_5_volume',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_6',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe8\x8d\xaf\xe7\x89\xa9\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_6_method',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe6\xb3\x95', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_6_period',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe8\x8d\xaf\xe6\x97\xb6\xe9\x97\xb4', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_6_take_medicine_compliance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe6\x9c\x8d\xe8\x8d\xaf\xe4\xbe\x9d\xe4\xbb\x8e\xe6\x80\xa7', choices=[('\u89c4\u5f8b', b'\xe8\xa7\x84\xe5\xbe\x8b'), ('\u95f4\u65ad', b'\xe9\x97\xb4\xe6\x96\xad'), ('\u4e0d\u670d\u836f', b'\xe4\xb8\x8d\xe6\x9c\x8d\xe8\x8d\xaf')]),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='take_medicine_6_volume',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe7\x94\xa8\xe9\x87\x8f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='urine_microalbumin',
            field=models.FloatField(null=True, verbose_name=b'\xe5\xb0\xbf\xe5\xbe\xae\xe9\x87\x8f\xe7\x99\xbd\xe8\x9b\x8b\xe7\x99\xbd', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccinate_suggestion',
            field=models.CharField(max_length=200, null=True, verbose_name=b'\xe5\x8d\xb1\xe9\x99\xa9\xe5\x9b\xa0\xe7\xb4\xa0\xe6\x8e\xa7\xe5\x88\xb6\xe2\x80\x94\xe2\x80\x94\xe5\xbb\xba\xe8\xae\xae\xe6\x8e\xa5\xe7\xa7\x8d\xe7\x96\xab\xe8\x8b\x97', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_date_1',
            field=models.DateField(null=True, verbose_name=b'\xe6\x8e\xa5\xe7\xa7\x8d\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_date_2',
            field=models.DateField(null=True, verbose_name=b'\xe6\x8e\xa5\xe7\xa7\x8d\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_date_3',
            field=models.DateField(null=True, verbose_name=b'\xe6\x8e\xa5\xe7\xa7\x8d\xe6\x97\xa5\xe6\x9c\x9f', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_institution_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x8e\xa5\xe7\xa7\x8d\xe6\x9c\xba\xe6\x9e\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_institution_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x8e\xa5\xe7\xa7\x8d\xe6\x9c\xba\xe6\x9e\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_institution_3',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe6\x8e\xa5\xe7\xa7\x8d\xe6\x9c\xba\xe6\x9e\x84', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_name_1',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb01', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_name_2',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb02', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vaccine_name_3',
            field=models.CharField(max_length=100, null=True, verbose_name=b'\xe5\x90\x8d\xe7\xa7\xb03', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vessel',
            field=models.ManyToManyField(to='ehr.VesselChoices', null=True, verbose_name=b'\xe8\xa1\x80\xe7\xae\xa1\xe7\x96\xbe\xe7\x97\x85', blank=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='bodyexam',
            name='vessel_extra',
            field=models.CharField(max_length=50, null=True, verbose_name=b'\xe8\xa1\x80\xe7\xae\xa1\xe7\x96\xbe\xe7\x97\x85\xe2\x80\x94\xe2\x80\x94\xe5\x85\xb6\xe4\xbb\x96', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='bodyexam',
            name='b_ultrasonic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'B\xe8\xb6\x85', choices=[('\u6b63\u5e38', b'\xe6\xad\xa3\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='bodyexam',
            name='lung_breath_sound',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'\xe5\x91\xbc\xe5\x90\xb8\xe9\x9f\xb3', choices=[('\u6b63\u5e38', b'\xe6\xad\xa3\xe5\xb8\xb8'), ('\u5f02\u5e38', b'\xe5\xbc\x82\xe5\xb8\xb8')]),
            preserve_default=True,
        ),
    ]
