# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from services.views import service_index

from vaccine import views
from .forms import *
from .preview import *


urlpatterns = patterns('',
    url(r'^$', views.vaccine_index, name='vaccine_index'),
    url(r'vaccine_card/$', VaccineCardFormPreview(VaccineCardForm),
        {'type_alias': 'vaccine', 'item_alias': 'vaccine_card', 'model_name': 'VaccineCard'},
        name='vaccine_card'),
    url(r'hepatitis_b_vaccine_1/$', VaccineFormPreview(HepatitisBVaccine1Form),
        {'type_alias': 'vaccine', 'item_alias': 'hepatitis_b_vaccine_1', 'model_name': 'HepatitisBVaccine1'},
        name='hepatitis_b_vaccine_1'),
    url(r'hepatitis_b_vaccine_2/$', VaccineFormPreview(HepatitisBVaccine2Form),
        {'type_alias': 'vaccine', 'item_alias': 'hepatitis_b_vaccine_2', 'model_name': 'HepatitisBVaccine2'},
        name='hepatitis_b_vaccine_2'),
    url(r'hepatitis_b_vaccine_3/$', VaccineFormPreview(HepatitisBVaccine3Form),
        {'type_alias': 'vaccine', 'item_alias': 'hepatitis_b_vaccine_3', 'model_name': 'HepatitisBVaccine3'},
        name='hepatitis_b_vaccine_3'),
    url(r'bcg_vaccine/$', VaccineFormPreview(BcgVaccineForm),
        {'type_alias': 'vaccine', 'item_alias': 'bcg_vaccine', 'model_name': 'BcgVaccine'},
        name='hepatitis_b_vaccine_3'),
    url(r'^poliomyelitis_vaccine_1/$', VaccineFormPreview(PoliomyelitisVaccine1Form),
        {'type_alias': 'vaccine', 'item_alias': 'poliomyelitis_vaccine_1', 'model_name': 'PoliomyelitisVaccine1'},
        name='poliomyelitis_vaccine_1'),
    url(r'^poliomyelitis_vaccine_2/$', VaccineFormPreview(PoliomyelitisVaccine2Form),
        {'type_alias': 'vaccine', 'item_alias': 'poliomyelitis_vaccine_2', 'model_name': 'PoliomyelitisVaccine2'},
        name='poliomyelitis_vaccine_2'),
    url(r'^poliomyelitis_vaccine_3/$', VaccineFormPreview(PoliomyelitisVaccine3Form),
        {'type_alias': 'vaccine', 'item_alias': 'poliomyelitis_vaccine_3', 'model_name': 'PoliomyelitisVaccine3'},
        name='poliomyelitis_vaccine_3'),
    url(r'^poliomyelitis_vaccine_4/$', VaccineFormPreview(PoliomyelitisVaccine4Form),
        {'type_alias': 'vaccine', 'item_alias': 'poliomyelitis_vaccine_4', 'model_name': 'PoliomyelitisVaccine4'},
        name='poliomyelitis_vaccine_4'),
    url(r'^diphtheria_pertussis_tetanus_1/$', VaccineFormPreview(DiphtheriaPertussisTetanus1Form),
        {'type_alias': 'vaccine', 'item_alias': 'diphtheria_pertussis_tetanus_1', 'model_name': 'DiphtheriaPertussisTetanus1'},
        name='diphtheria_pertussis_tetanus_1'),
    url(r'^diphtheria_pertussis_tetanus_2/$', VaccineFormPreview(DiphtheriaPertussisTetanus2Form),
        {'type_alias': 'vaccine', 'item_alias': 'diphtheria_pertussis_tetanus_2', 'model_name': 'DiphtheriaPertussisTetanus2'},
        name='diphtheria_pertussis_tetanus_2'),
    url(r'^diphtheria_pertussis_tetanus_3/$', VaccineFormPreview(DiphtheriaPertussisTetanus3Form),
        {'type_alias': 'vaccine', 'item_alias': 'diphtheria_pertussis_tetanus_3', 'model_name': 'DiphtheriaPertussisTetanus3'},
        name='diphtheria_pertussis_tetanus_3'),
    url(r'^diphtheria_pertussis_tetanus_4/$', VaccineFormPreview(DiphtheriaPertussisTetanus4Form),
        {'type_alias': 'vaccine', 'item_alias': 'diphtheria_pertussis_tetanus_4', 'model_name': 'DiphtheriaPertussisTetanus4'},
        name='diphtheria_pertussis_tetanus_4'),
    url(r'^diphtheria_tetanus_vaccine/$', VaccineFormPreview(DiphtheriaTetanusVaccineForm),
        {'type_alias': 'vaccine', 'item_alias': 'diphtheria_tetanus_vaccine', 'model_name': 'DiphtheriaTetanusVaccine'},
        name='diphtheria_tetanus_vaccine'),
    url(r'^measles_rubella/$', VaccineFormPreview(MeaslesRubellaForm),
        {'type_alias': 'vaccine', 'item_alias': 'measles_rubella', 'model_name': 'MeaslesRubella'},
        name='measles_rubella'),
    url(r'^measles_mumps_rubella_1/$', VaccineFormPreview(MeaslesMumpsRubella1Form),
        {'type_alias': 'vaccine', 'item_alias': 'measles_mumps_rubella_1', 'model_name': 'MeaslesMumpsRubella1'},
        name='measles_mumps_rubella_1'),
    url(r'^measles_mumps_rubella_2/$', VaccineFormPreview(MeaslesMumpsRubella2Form),
        {'type_alias': 'vaccine', 'item_alias': 'measles_mumps_rubella_2', 'model_name': 'MeaslesMumpsRubella2'},
        name='measles_mumps_rubella_2'),
    url(r'^measles_mumps/$', VaccineFormPreview(MeaslesMumpsForm),
        {'type_alias': 'vaccine', 'item_alias': 'measles_mumps', 'model_name': 'MeaslesMumps'},
        name='measles_mumps'),
    url(r'^measles_1/$', VaccineFormPreview(Measles1Form),
        {'type_alias': 'vaccine', 'item_alias': 'measles_1', 'model_name': 'Measles1'},
        name='measles_1'),
    url(r'^measles_2/$', VaccineFormPreview(Measles2Form),
        {'type_alias': 'vaccine', 'item_alias': 'measles_2', 'model_name': 'Measles2'},
        name='measles_2'),
    url(r'^meningitis_a_1/$', VaccineFormPreview(MeningitisA1Form),
        {'type_alias': 'vaccine', 'item_alias': 'meningitis_a_1', 'model_name': 'MeningitisA1'},
        name='meningitis_a_1'),
    url(r'^meningitis_a_2/$', VaccineFormPreview(MeningitisA2Form),
        {'type_alias': 'vaccine', 'item_alias': 'meningitis_a_2', 'model_name': 'MeningitisA2'},
        name='meningitis_ac_2'),
    url(r'^meningitis_ac_1/$', VaccineFormPreview(MeningitisAc1Form),
        {'type_alias': 'vaccine', 'item_alias': 'meningitis_ac_1', 'model_name': 'MeningitisAc1'},
        name='meningitis_ac_1'),
    url(r'^meningitis_ac_2/$', VaccineFormPreview(MeningitisAc2Form),
        {'type_alias': 'vaccine', 'item_alias': 'meningitis_ac_2', 'model_name': 'MeningitisAc2'},
        name='meningitis_ac_2'),
    url(r'^japanese_encephalitis_attenuated_1/$', VaccineFormPreview(JapaneseEncephalitisAttenuated1Form),
        {'type_alias': 'vaccine', 'item_alias': 'japanese_encephalitis_attenuated_1', 'model_name': 'JapaneseEncephalitisAttenuated1'},
        name='japanese_encephalitis_attenuated_1'),
    url(r'^japanese_encephalitis_attenuated_2/$', VaccineFormPreview(JapaneseEncephalitisAttenuated2Form),
        {'type_alias': 'vaccine', 'item_alias': 'japanese_encephalitis_attenuated_2', 'model_name': 'JapaneseEncephalitisAttenuated2'},
        name='japanese_encephalitis_attenuated_2'),
    url(r'^japanese_encephalitis_inactivated_1/$', VaccineFormPreview(JapaneseEncephalitisInactivated1Form),
        {'type_alias': 'vaccine', 'item_alias': 'japanese_encephalitis_inactivated_1', 'model_name': 'JapaneseEncephalitisInactivated1'},
        name='japanese_encephalitis_inactivated_1'),
    url(r'^japanese_encephalitis_inactivated_2/$', VaccineFormPreview(JapaneseEncephalitisInactivated2Form),
        {'type_alias': 'vaccine', 'item_alias': 'japanese_encephalitis_inactivated_2', 'model_name': 'JapaneseEncephalitisInactivated2'},
        name='japanese_encephalitis_inactivated_2'),
    url(r'^japanese_encephalitis_inactivated_3/$', VaccineFormPreview(JapaneseEncephalitisInactivated3Form),
        {'type_alias': 'vaccine', 'item_alias': 'japanese_encephalitis_inactivated_3', 'model_name': 'JapaneseEncephalitisInactivated3'},
        name='japanese_encephalitis_inactivated_3'),
    url(r'^japanese_encephalitis_inactivated_4/$', VaccineFormPreview(JapaneseEncephalitisInactivated4Form),
        {'type_alias': 'vaccine', 'item_alias': 'japanese_encephalitis_inactivated_4', 'model_name': 'JapaneseEncephalitisInactivated4'},
        name='japanese_encephalitis_inactivated_4'),
    url(r'^hepatitis_a_attenuated/$', VaccineFormPreview(HepatitisAAttenuatedForm),
        {'type_alias': 'vaccine', 'item_alias': 'hepatitis_a_attenuated', 'model_name': 'HepatitisAAttenuated'},
        name='hepatitis_a_attenuated'),
    url(r'^hepatitis_a_inactivated_1/$', VaccineFormPreview(HepatitisAInactivated1Form),
        {'type_alias': 'vaccine', 'item_alias': 'hepatitis_a_inactivated_1', 'model_name': 'HepatitisAInactivated1'},
        name='hepatitis_a_inactivated_1'),
    url(r'^hepatitis_a_inactivated_2/$', VaccineFormPreview(HepatitisAInactivated2Form),
        {'type_alias': 'vaccine', 'item_alias': 'hepatitis_a_inactivated_2', 'model_name': 'HepatitisAInactivated2'},
        name='hepatitis_a_inactivated_2'),
    url(r'^anthrax_vaccine/$', VaccineFormPreview(AnthraxVaccineForm),
        {'type_alias': 'vaccine', 'item_alias': 'anthrax_vaccine', 'model_name': 'AnthraxVaccine'},
        name='anthrax_vaccine'),
    url(r'^leptospira_vaccine_1/$', VaccineFormPreview(LeptospiraVaccine1Form),
        {'type_alias': 'vaccine', 'item_alias': 'leptospira_vaccine_1', 'model_name': 'LeptospiraVaccine1'},
        name='leptospira_vaccine_1'),
    url(r'^leptospira_vaccine_2/$', VaccineFormPreview(LeptospiraVaccine2Form),
        {'type_alias': 'vaccine', 'item_alias': 'leptospira_vaccine_2', 'model_name': 'LeptospiraVaccine2'},
        name='leptospira_vaccine_2'),
    url(r'^leptospira_vaccine_2/$', VaccineFormPreview(LeptospiraVaccine2Form),
        {'type_alias': 'vaccine', 'item_alias': 'leptospira_vaccine_2', 'model_name': 'LeptospiraVaccine2'},
        name='leptospira_vaccine_2'),
    url(r'^hemorrhagic_i_ii_1/$', VaccineFormPreview(HemorrhagicIII1Form),
        {'type_alias': 'vaccine', 'item_alias': 'hemorrhagic_i_ii_1', 'model_name': 'HemorrhagicIII1'},
        name='hemorrhagic_i_ii_1'),
    url(r'^hemorrhagic_i_ii_2/$', VaccineFormPreview(HemorrhagicIII2Form),
        {'type_alias': 'vaccine', 'item_alias': 'hemorrhagic_i_ii_2', 'model_name': 'HemorrhagicIII2'},
        name='hemorrhagic_i_ii_2'),
    url(r'^hemorrhagic_i_ii_3/$', VaccineFormPreview(HemorrhagicIII3Form),
        {'type_alias': 'vaccine', 'item_alias': 'hemorrhagic_i_ii_3', 'model_name': 'HemorrhagicIII3'},
        name='hemorrhagic_i_ii_3'),

    url(r'^vaccine_page/$', views.vaccine_page, name='vaccine_page'),

    url(r'^vaccine_records/$', views.vaccine_records, name='vaccine_records'),
    url(r'^vaccine_card_head/$', views.vaccine_card_head, name='vaccine_card_head'),
    url(r"^vaccine_card_head_save/$", views.vaccine_card_head_save, name='vaccine_card_head_save'),
    url(r"^vaccinate_submit/$", views.vaccinate_submit, name='vaccinate_submit'),

)



